"""Shared fixtures and gcode builders.

The gcode fixtures are written at test time rather than committed as files so
that the exact bytes each slicer flavour is expected to emit are visible right
next to the assertions about them.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from spool.db import add_spool, connect
from spool.models import Printer, Spool

# --------------------------------------------------------------------------
# Synthetic gcode, one builder per slicer flavour
# --------------------------------------------------------------------------

#: A few hundred bytes of plausible movement commands, so the metadata is not
#: sitting alone in a two line file.
_BODY = "\n".join(
    "G1 X%0.2f Y%0.2f E%0.4f F1800" % (i * 0.37, i * 0.41, i * 0.0021) for i in range(40)
)


def prusaslicer_gcode() -> str:
    """PrusaSlicer 2.8 output: banner on top, estimates in the footer."""
    return (
        "; generated by PrusaSlicer 2.8.0+linux-x64 on 2026-03-02 at 10:00:00 UTC\n"
        ";\n"
        "M104 S215 ; set temperature\n"
        + _BODY
        + "\n"
        "; filament used [mm] = 4321.0\n"
        "; filament used [cm3] = 10.39\n"
        "; filament used [g] = 12.88\n"
        "; total filament used [g] = 12.88\n"
        "; estimated printing time (normal mode) = 1h 2m 3s\n"
        "; filament_type = PLA\n"
        "; filament_diameter = 1.75\n"
        "; filament_density = 1.24\n"
        "; prusaslicer_config = end\n"
    )


def superslicer_gcode() -> str:
    """SuperSlicer: same comment grammar, different banner, days in the time."""
    return (
        "; generated by SuperSlicer 2.5.59.2 on 2026-03-04 at 08:15:00\n"
        + _BODY
        + "\n"
        "; filament used [mm] = 90210.5\n"
        "; filament used [g] = 268.9\n"
        "; estimated printing time (normal mode) = 1d 4h 30m 10s\n"
        "; filament_type = PETG\n"
        "; filament_diameter = 1.75\n"
    )


def orcaslicer_gcode() -> str:
    """OrcaSlicer: PrusaSlicer-style keys, colon-delimited total time."""
    return (
        "; generated by OrcaSlicer 2.0.0 on 2026-03-06 at 12:00:00\n"
        + _BODY
        + "\n"
        "; filament used [mm] = 15250.4\n"
        "; filament used [cm3] = 36.7\n"
        "; total filament used [g] = 45.51\n"
        "; model printing time: 3h 12m 40s; total estimated time: 3h 20m 5s\n"
        "; filament_type = PLA\n"
    )


def bambustudio_gcode() -> str:
    """Bambu Studio: an Orca relative, multi-extruder comma separated values."""
    return (
        "; generated by BambuStudio 1.9.5 on 2026-03-07 at 19:30:00\n"
        + _BODY
        + "\n"
        "; filament used [mm] = 3000.0, 1500.0\n"
        "; filament used [g] = 9.00, 4.50\n"
        "; total estimated time: 2h 5m 0s\n"
        "; filament_type = PLA,PLA\n"
    )


def cura_gcode() -> str:
    """Cura: metres for filament, whole seconds for time, no grams at all."""
    return (
        ";FLAVOR:Marlin\n"
        ";TIME:3723\n"
        ";Filament used: 4.321m\n"
        ";Layer height: 0.2\n"
        ";Generated with Cura_SteamEngine 5.6.0\n"
        + _BODY
        + "\n"
        ";End of Gcode\n"
    )


def cura_multi_gcode() -> str:
    """Cura with two extruders: filament lengths are comma separated."""
    return (
        ";FLAVOR:Marlin\n"
        ";TIME:7200\n"
        ";Filament used: 3.0m, 1.5m\n"
        ";Generated with Cura_SteamEngine 5.6.0\n"
        + _BODY
        + "\n"
    )


def bare_gcode() -> str:
    """Hand-written or post-processed gcode with no slicer metadata at all."""
    return "M104 S200\nG28\n" + _BODY + "\nM104 S0\nM84\n"


#: Every flavour builder, for parametrised tests.
FLAVOR_BUILDERS = {
    "prusaslicer": prusaslicer_gcode,
    "superslicer": superslicer_gcode,
    "orcaslicer": orcaslicer_gcode,
    "bambustudio": bambustudio_gcode,
    "cura": cura_gcode,
}


@pytest.fixture
def write_gcode(tmp_path: Path):
    """Return a helper that writes gcode text to a temp file and returns it."""

    def _write(name: str, text: str) -> Path:
        path = tmp_path / name
        path.write_text(text, encoding="utf-8")
        return path

    return _write


# --------------------------------------------------------------------------
# Database fixtures
# --------------------------------------------------------------------------


@pytest.fixture
def db_path(tmp_path: Path) -> Path:
    """Path to a database file inside the test's temp directory."""
    return tmp_path / "spool.db"


@pytest.fixture
def conn(db_path: Path):
    """An initialised, migrated connection that is closed after the test."""
    connection = connect(db_path)
    try:
        yield connection
    finally:
        connection.close()


@pytest.fixture
def pla_spool() -> Spool:
    """A round-numbers spool: 1 kg for 25.00, so a gram costs exactly 0.025."""
    return Spool(
        material="PLA",
        brand="Testament",
        color="Signal Orange",
        diameter_mm=1.75,
        spool_weight_g=1000.0,
        density_g_cm3=1.24,
        price=25.00,
        currency="USD",
        purchased="2026-01-01",
    )


@pytest.fixture
def petg_spool() -> Spool:
    """A second spool with a different material and price."""
    return Spool(
        material="PETG",
        brand="Overture",
        color="Grey",
        diameter_mm=1.75,
        spool_weight_g=1000.0,
        price=20.00,
        currency="USD",
        purchased="2026-01-15",
    )


@pytest.fixture
def stored_spools(conn, pla_spool: Spool, petg_spool: Spool) -> list[Spool]:
    """Both spools, persisted, with ids assigned."""
    return [add_spool(conn, pla_spool), add_spool(conn, petg_spool)]


@pytest.fixture
def voron() -> Printer:
    """A printer with round numbers: 150 W and 0.30 per hour of wear."""
    return Printer(name="Voron 2.4", watts=150.0, price=900.0, life_hours=3000.0)


@pytest.fixture
def fixture_jobs_file(tmp_path: Path) -> Path:
    """A small FixtureSource file covering success, failure and cancellation."""
    payload = {
        "jobs": [
            {
                "id": "fx-1",
                "name": "benchy.gcode",
                "printer": "Voron 2.4",
                "filament_g": 12.9,
                "duration_s": 3723,
                "status": "success",
                "started": "2026-01-08T18:20:00+00:00",
            },
            {
                "id": "fx-2",
                "name": "bracket.gcode",
                "printer": "Voron 2.4",
                "filament_g": 100.0,
                "duration_s": 14400,
                "status": "failed",
                "failed_at_fraction": 0.4,
                "started": "2026-02-11T09:00:00+00:00",
            },
            {
                "id": "fx-3",
                "name": "test-cube.gcode",
                "printer": "Prusa MK4",
                "length_mm": 1000.0,
                "duration_s": 600,
                "status": "cancelled",
                "failed_at": 0.5,
                "started": 1772000000,
            },
        ]
    }
    path = tmp_path / "jobs.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path
